// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _03_EntityFramework_CodeFirst_2.Context;

#nullable disable

namespace _03_EntityFramework_CodeFirst_2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251222180201_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DersOgrenci", b =>
                {
                    b.Property<int>("DerssId")
                        .HasColumnType("int");

                    b.Property<int>("OgrencisId")
                        .HasColumnType("int");

                    b.HasKey("DerssId", "OgrencisId");

                    b.HasIndex("OgrencisId");

                    b.ToTable("DersOgrenci");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.DersOgrenci", b =>
                {
                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("DersId", "OgrenciId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("DersOgrenciler");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.Mudur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Maas")
                        .HasColumnType("float");

                    b.Property<string>("Soyad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Mudurler");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TCId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SinifId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.Ogretmen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Brans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Ogretmenler");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.Sinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Sube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.TC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId")
                        .IsUnique();

                    b.ToTable("TC");
                });

            modelBuilder.Entity("DersOgrenci", b =>
                {
                    b.HasOne("_03_EntityFramework_CodeFirst_2.Entities.Ders", null)
                        .WithMany()
                        .HasForeignKey("DerssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_03_EntityFramework_CodeFirst_2.Entities.Ogrenci", null)
                        .WithMany()
                        .HasForeignKey("OgrencisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.DersOgrenci", b =>
                {
                    b.HasOne("_03_EntityFramework_CodeFirst_2.Entities.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_03_EntityFramework_CodeFirst_2.Entities.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.Ogrenci", b =>
                {
                    b.HasOne("_03_EntityFramework_CodeFirst_2.Entities.Sinif", "Sinif")
                        .WithMany("Ogrencis")
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.TC", b =>
                {
                    b.HasOne("_03_EntityFramework_CodeFirst_2.Entities.Ogrenci", "Ogrenci")
                        .WithOne("TC")
                        .HasForeignKey("_03_EntityFramework_CodeFirst_2.Entities.TC", "OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.Ogrenci", b =>
                {
                    b.Navigation("TC")
                        .IsRequired();
                });

            modelBuilder.Entity("_03_EntityFramework_CodeFirst_2.Entities.Sinif", b =>
                {
                    b.Navigation("Ogrencis");
                });
#pragma warning restore 612, 618
        }
    }
}
